
trigger:
- development

pr:
  branches:
    include:
    - development
    - releases/*
  paths:
    include:
    - "*"
    exclude:
    - airflow-local
  drafts: true # whether to build draft PRs, defaults to true

steps:
- script: sudo apt-get update && sudo apt-get install -y libpython3.9-dev
  displayName: 'install libpython'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: python -m pip install -r requirements-dev.txt
  displayName: 'Install requirements-dev'

- script: python -m pip install pytest-azurepipelines~=1.0.4
  displayName: 'Install pytest-azurepipelines'

- script: mypy dags/benk
  displayName: 'Run MyPy'

- script: >
    python -m pytest
    --doctest-modules 
    --junitxml=junit/test-results.xml 
    --cov-report=xml
    tests/
  displayName: 'Run PyTest'

- script: black --check dags/benk
  displayName: 'Run Black'

- script: flake8 dags/benk
  displayName: 'Run Flake8'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
