version: "3.7"

services:
  benk-airflow-test:
    image: benk-airflow-test
    container_name: benk-airflow-test

    # specify platform: linux/<arm64/v8|amd64>
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "./test.sh"
