[[tool.mypy.overrides]]
module = "airflow.providers.cncf.kubernetes.operators.kubernetes_pod.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "kubernetes.client.*"
ignore_missing_imports = true

[tool.mypy]
plugins = ["pydantic.mypy"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = false
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.isort]
profile = "black"
skip_gitignore = true
