[tool.black]
line-length = 120
color = true
verbose = true

[tool.coverage.report]
show_missing = true
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # ignore type checking
    "if TYPE_CHECKING:",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod"
]

[tool.flake8]
exclude = ["tests"]
max-complexity = 6
max-line-length = 120
show_source = true
ignore = [
    # Missing docstring in __init__
    "D107",
    # Missing docstring in public package
    "D104",
    # Missing docstring in module
    "D100",
    # line break before binary operator
    "W503"
]

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
follow_imports = "normal"
pretty = true
cache_dir = "/tmp/.mypy_cache"

# These options below can be replaced by 'strict = true' when all true
# Start off with these
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true

# Getting these passing should be easy
strict_equality = true
extra_checks = true

# Strongly recommend enabling this one as soon as you can
check_untyped_defs = true

# These shouldn't be too much additional work, but may be tricky to
# get passing if you use a lot of untyped libraries
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = true

# These next few are various gradations of forcing use of type annotations
disallow_untyped_calls = false
disallow_incomplete_defs = false
disallow_untyped_defs = false

# This one isn't too hard to get passing, but return on investment is lower
no_implicit_reexport = true

# This one can be tricky to get passing if you use a lot of untyped libraries
warn_return_any = true

[[tool.mypy.overrides]]
module = "airflow.providers.cncf.kubernetes.operators.kubernetes_pod.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "kubernetes.client.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pydantic.*"]
ignore_missing_imports = true
ignore_errors = true

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "dags"
cache_dir = "/tmp/.pytest_cache"
addopts = [
    "--capture=no",
    "--doctest-modules",
    "--cache-clear",
    "--import-mode=importlib"
]
env = [
    "AIRFLOW_VAR_POD-NAMESPACE=test_airflow",
    "AIRFLOW_VAR_POD-CONTAINER-REGISTRY-URL=test_registry",
    "AIRFLOW_VAR_POD-GOB-SHARED-STORAGE-CLAIM=",
    "AIRFLOW_VAR_POD-GOB-UPLOAD-IMAGE-NAME=",
    "AIRFLOW_VAR_POD-GOB-UPLOAD-IMAGE-TAG=",
    "AIRFLOW_VAR_POD-GOB-IMPORT-IMAGE-NAME=",
    "AIRFLOW_VAR_POD-GOB-IMPORT-IMAGE-TAG=",
    "AIRFLOW_VAR_GOB-SHARED-DIR",
    "AIRFLOW_VAR_GOB-DATABASE-USER=gob",
    "AIRFLOW_VAR_GOB-DATABASE-NAME=gob",
    "AIRFLOW_VAR_GOB-DATABASE-PASSWORD=insecure",
    "AIRFLOW_VAR_GOB-DATABASE-HOST-OVERRIDE=host",
    "AIRFLOW_VAR_GOB-DATABASE-PORT-OVERRIDE=5432",
    # Grondslag
    "AIRFLOW_VAR_GRONDSLAG-PASSWORD=",
    "AIRFLOW_VAR_GRONDSLAG-USER=",
    "AIRFLOW_VAR_GRONDSLAG-PORT=",
    "AIRFLOW_VAR_GRONDSLAG-DB=",
    "AIRFLOW_VAR_GRONDSLAG-HOST=",
    # DGDialog
    "AIRFLOW_VAR_DGDIALOG-PASSWORD=",
    "AIRFLOW_VAR_DGDIALOG-USER=",
    "AIRFLOW_VAR_DGDIALOG-PORT=",
    "AIRFLOW_VAR_DGDIALOG-DB=",
    "AIRFLOW_VAR_DGDIALOG-HOST=",
    # objectstore
    "AIRFLOW_VAR_OBJECTSTORE-GOB-TENANTID=",
    "AIRFLOW_VAR_OBJECTSTORE-GOB-PASSWORD=",
    "AIRFLOW_VAR_OBJECTSTORE-GOB-TENANTNAME=",
    "AIRFLOW_VAR_OBJECTSTORE-GOB-USER=",
    # objectstore
    "AIRFLOW_VAR_OBJECTSTORE-BI-TENANTID=",
    "AIRFLOW_VAR_OBJECTSTORE-BI-PASSWORD=",
    "AIRFLOW_VAR_OBJECTSTORE-BI-TENANTNAME=",
    "AIRFLOW_VAR_OBJECTSTORE-BI-USER=",
    # Neuron
    "AIRFLOW_VAR_NEURON-DATABASE=",
    "AIRFLOW_VAR_NEURON-HOST=",
    "AIRFLOW_VAR_NEURON-PASSWORD=",
    "AIRFLOW_VAR_NEURON-PORT=",
    "AIRFLOW_VAR_NEURON-USER=",
    # GOB Prepare DB
    "AIRFLOW_VAR_GOB-PREPARE-DATABASE=",
    "AIRFLOW_VAR_GOB-PREPARE-DATABASE-HOST=",
    "AIRFLOW_VAR_GOB-PREPARE-DATABASE-PASSWORD=",
    "AIRFLOW_VAR_GOB-PREPARE-DATABASE-PORT=",
    "AIRFLOW_VAR_GOB-PREPARE-DATABASE-USER=",
    # SFTP IBZ
    "SFTP_IBURGERZAKEN_UID=ibz_uid",
    "SFTP_IBURGERZAKEN_UID_PWD=ibz_pw",
    "DB_IBURGERZAKEN_SERVER=ibz_server",
    # SFTP GOB
    "GOB_OBJECTSTORE_TENANTID=gob_tenant",
    "GOB_OBJECTSTORE_USER=gob_user",
    "GOB_OBJECTSTORE_PWD=gob_pw"
]
