[[tool.mypy.overrides]]
module = "airflow.providers.cncf.kubernetes.operators.kubernetes_pod.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "kubernetes.client.*"
ignore_missing_imports = true

[tool.mypy]
exclude = ["benk.definitions.pydantic"]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

[tool.isort]
profile = "black"
skip_gitignore = true
