# Configure airflow to use the created volume
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: manual
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    existingClaim: dag-source-dir-claim

#config:
#  secrets:
#    backend: airflow.secrets.local_filesystem.LocalFilesystemBackend
#    backend_kwargs: {"variables_file_path": "/files/var.json", "connections_file_path": "/files/conn.json" }
